
server:
   port: 8081
    
security:
   firebase-props:
     database-url: https://frontend-project-bd2e2-default-rtdb.firebaseio.com/
     enable-strict-server-session: false
     enable-check-session-revoked: false
     enable-logout-everywhere: false
     session-expiry-in-days: 5
   cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: ${CORS_DOMAIN}
    path: /
   allow-credentials: true
   allowed-origins:
   - https://${CORS_DOMAIN}
   - http://localhost:3000
   allowed-methods:
   - GET
   - POST
   - PUT
   - PATCH
   - DELETE
   - OPTIONS
   allowed-headers:
   - Authorization
   - Origin
   - Content-Type
   - Accept
   - Accept-Encoding
   - Accept-Language
   - Access-Control-Allow-Origin
   - Access-Control-Allow-Headers
   - Access-Control-Request-Method
   - X-Requested-With
   - X-Auth-Token
   - X-Xsrf-Token
   - Cache-Control
   - Id-Token
   allowed-public-apis:
   - /favicon.ico
   - /session/login
   - /public/*
   - /h2-console
   - /test/**
   - /context-path/v3/api-docs
   - /v3/api-docs
   exposed-headers:
   - X-Xsrf-Token
   valid-application-roles:
   - ROLE_SUPER
   - ROLE_ADMIN
   - ROLE_SELLER
   - ROLE_CUSTOMER
   super-admins: ${SUPER_ADMINS}
   test:
     login:
       enabled: false
logging:
   level:
      root: WARN
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR
      io:
        thepro: DEBUG
   pattern:
     console: "%d{HH:mm:ss} || %highlight(%5p) < %highlight(%-35.35logger{35}) > %highlight(%m%n)"
spring: 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.ddl-auto: update
active-mq:
  broker-url : http://127.0.0.1:8161/
  topic: e-bidding
 
    